app/__init__.py
from flask import Flask


def create_app():
    app=Flask(__name__)
    from app.routes import main
    
    app.register_blueprint(main)
    return app

    

app/routes.py
from flask import Blueprint, render_template,Response,stream_template,stream_with_context

from video_processing.genrate_frame import  genrate_frames,genrate_frame,flies_number
import time

main = Blueprint('main', __name__)

@main.route('/')
def index():
     number = next(flies_number())
     return render_template('index.html', number=number)


@main.route('/live')
def live():
    return Response(genrate_frame(),mimetype='multipart/x-mixed-replace; boundary=frame')


@main.route('/video_feed')
def video_feed():
    return Response(genrate_frames(),mimetype='multipart/x-mixed-replace; boundary=frame')

@main.route('/number_of_flies')

def number_of_flies():
     number=next(flies_number())
     return Response(number,mimetype='multipart/x-mixed-replace; boundary=frame')
     
    
    
    

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Object Detection</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            padding: 20px;
            background-color: #333;
            color: #fff;
            margin: 0;
        }

        .d {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            flex-direction: column;
        }
    </style>
</head>
<body>

    <h1>Video Stream</h1>
    <h1 > number of flies is : {{number}} </h1>
    <div class="d">
        
        <img src="{{ url_for('main.video_feed') }}" width="720">
    </div>

    

</body>
</html>